project:
  type: website
  output-dir: docs

website:
  title: "GLMakie Gallery"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://math4mad.github.io/plots-gallery/
        text: Github
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - section: "Math"
        contents: math/*
      - section: "Statistics"
        contents: statistics/*
      - section: "Machine Learning"
        contents: machinelearning/*
      - section: "Data Viz"
        contents: vis/*
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
      

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

